language: python
python:
    - "3.5"
#    - "3.3"
#    - "3.4"
#    - "nightly"

# install dependencies
# we have to upgrade pip to accept the .[dev] option
install:
    - pip install pip -U
    - pip install .[dev] -r requirements.txt
    - pip install coveralls pytest-cov

# run tests
script:
    - py.test src/smallvectors/tests/

after_success:
    - coveralls